version: "3.3"

services:
  db:
    image: mongo:4.0.1
    restart: always
    networks:
      - back-network
    volumes:
      - /opt/mongo-volume:/data/db

  api:
    build:
      context: ./tours-0219-js-westendorp-api
    restart: always 
    environment:
      - UPLOAD_PATH=/tmp/upload
      - NODE_ENV=production
      - PORT=3000
      - SECRET_KEY=${SECRET}
      - DBURI=mongodb://db/Westendorp?retryWrites=true
    networks:
      - web
      - back-network
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ce-westendop.com;PathPrefix:/api,/images"
      - "traefik.port=3000"
      - "traefik.docker.network=web"

  ui:
    build:
      context: ./tours-0219-js-westendorp-ui
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=80
    networks:
      - web
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ce-westendop.com"
      - "traefik.port=80"
      - "traefik.docker.network=web"

networks:
  web:
      external: true
  back-network:

volumes:
  mongo-volume:
    driver: "local"